# Dockerfile.frontend
# build static with node, serve with nginx
FROM node:18-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
# Vite production build
RUN npm run build

FROM nginx:stable-alpine
# 将 build 出来的静态文件放到 nginx 的默认目录
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
