spring.application.name=spring-ai-zinkt
server.port=${SERVER_PORT}

spring.ai.dashscope.api-key=${QWEN_API_KEY}
spring.ai.dashscope.chat.options.model=qwen-plus
spring.ai.dashscope.embedding.options.model=text-embedding-v4
spring.ai.dashscope.embedding.options.dimensions=1536

# PostgreSQL ?????
spring.datasource.url=${PGSQL_URL}
spring.datasource.username=${PGSQL_USERNAME}
spring.datasource.password=${PGSQL_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
# vector store
#spring.ai.vectorstore.pgvector.max-document-batch-size=
spring.ai.vectorstore.pgvector.dimensions=1536

# ??????????????
spring.profiles.active=init-vectorstore

spring.ai.chat.memory.repository.jdbc.initialize-schema=always
spring.ai.chat.memory.repository.jdbc.schema=classpath:org/springframework/ai/chat/memory/repository/jdbc/schema-@@platform@@.sql

# mcp
spring.ai.mcp.client.stdio.servers-configuration=classpath:mcp/servers-config.json

# Redis ??
spring.data.redis.host=localhost
spring.data.redis.port=6379

# log
logging.level.org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor=debug

#management.endpoints.web.exposure.include=beans